---
enabled: true
app:
  name: order-processor
  version: 1.0.0-SNAPSHOT
  namespace: quarkus-dev
  container:
    port: 8080
  route: true
  runtime: 
    name: openjdk-11-ubi8
    version: openjdk-11-ubi8
  buildconfig: true
  # pipeline:
    # imagestream: registry.access.redhat.com/ubi8/openjdk-11:1.11
  git:
    repo: https://github.com/quarkus-sre/order-processor
    revision: main

