{{- if .Values.enabled }}
{{- if .Values.app }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    pipeline.openshift.io/runtime: {{ .Values.app.pipeline.runtime.name }}
    pipeline.openshift.io/runtime-version: {{ .Values.app.pipeline.runtime.version }}
    pipeline.openshift.io/type: kubernetes
spec:
  params:
    - name: APP_NAME
      type: string
      default: {{ .Values.app.name }}
    - name: GIT_REPO
      type: string
      default: '{{ .Values.app.git.repo }}'
    - name: GIT_REVISION
      type: string
      default: {{ .Values.app.git.revision }}
    - name: IMAGE_NAME
      type: string
      default: >-
        image-registry.openshift-image-registry.svc:5000/{{ .Values.app.namespace }}/{{ .Values.app.name }}
    - name: PATH_CONTEXT
      type: string
      default: .
    - name: VERSION
      type: string
      default: {{ .Values.app.pipeline.runtime.version }}
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout status deploy/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
{{- end }}
{{- end }}
